mkdir -p .github/workflows
cat > .github/workflows/ci.yml << 'YAML'
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8 || true
      - name: Lint (soft)
        run: |
          flake8 TECH_CHALLENGE || true
      - name: Sanity checks
        run: |
          python -c "print('✅ CI OK')"
YAML
